In [85]:
import pandas as pd

In [86]:
from numpy import NaN, NAN, nan

In [87]:
import matplotlib
%matplotlib inline

In [83]:
marrakai0816 = pd.read_excel('../Land_Use/08-16_change_over_time_EDIT.xlsx')

In [84]:
marrakai0816.head()

   LU_CODE_08  08_AREA  LU_CODE_16  COMMOD       16_AREA
0           0      0.0         652          1.370713e+06
1           0      0.0         210  cattle  1.158460e+07
2           0      0.0         652          1.427609e+05
3           0      0.0         113          3.356297e+04
4           0      0.0         652          7.526508e+05

In [58]:
marrakai0816.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 795 entries, 0 to 794
Data columns (total 5 columns):
LU_CODE_08    795 non-null int64
08_AREA       795 non-null float64
LU_CODE_16    795 non-null int64
COMMOD        795 non-null object
16_AREA       795 non-null float64
dtypes: float64(2), int64(2), object(1)
memory usage: 31.1+ KB

In [57]:
marrakai0816.describe()

       LU_CODE_08        08_AREA  LU_CODE_16       16_AREA
count  795.000000     795.000000  795.000000  7.950000e+02
mean   114.540881   24570.541706  476.396226  4.201152e+05
std    194.464411   56000.199188  104.255959  1.771465e+06
min      0.000000       0.000000  113.000000  2.154370e+02
25%      0.000000       0.000000  453.000000  1.212597e+04
50%      0.000000       0.000000  512.000000  3.123038e+04
75%    440.000000   12745.953220  543.000000  8.152916e+04
max    460.000000  254160.997997  654.000000  1.865889e+07

In [33]:
marrakai0816.groupby('LU_CODE_08')['08_AREA'].sum()

LU_CODE_08
0      0.000000e+00
440    3.216970e+06
441    8.629583e+06
450    4.249394e+06
460    3.437634e+06
Name: 08_AREA, dtype: float64

In [62]:
test = marrakai0816.groupby(['LU_CODE_16'])['16_AREA'].sum()

In [63]:
test.head()

LU_CODE_16
113    2.115370e+07
125    1.500568e+07
133    2.242812e+07
210    1.421016e+08
320    2.349640e+06
Name: 16_AREA, dtype: float64

In [73]:
df = marrakai0816.groupby(['LU_CODE_08', 'LU_CODE_16'])['16_AREA'].sum()

In [75]:
test2.head()

LU_CODE_08  LU_CODE_16
0           113           2.115370e+07
            125           1.500568e+07
            133           1.236465e+07
            210           1.156794e+08
            320           1.612920e+06
Name: 16_AREA, dtype: float64

In [77]:
test2.iloc[1]

15005684.999676179

In [82]:
marrakai081.groupby(['LU_CODE_08', 'LU_CODE_16'])['08_AREA'].mean()

NameError: name 'marrakai081' is not defined

In [35]:
df=pd.read_excel('../Land_Use/08-16_change_over_time_EDIT.xlsx')

In [43]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 795 entries, 0 to 794
Data columns (total 5 columns):
LU_CODE_08    795 non-null int64
08_AREA       795 non-null float64
LU_CODE_16    795 non-null int64
COMMOD        795 non-null object
16_AREA       795 non-null float64
dtypes: float64(2), int64(2), object(1)
memory usage: 31.1+ KB

In [10]:
df = pd.read_excel('../Land_Use/Final_08-16_change_over_time.xlsx')

In [71]:
df.head()

   LU_CODE_08  08_AREA  LU_CODE_16  COMMOD      16_AREA
0           0      0.0         652           1370712.55
1           0      0.0         210  cattle  11584595.65
2           0      0.0         652            142760.94
3           0      0.0         113             33562.97
4           0      0.0         652            752650.83

In [72]:
marrakai0816.head(5)

   LU_CODE_08  08_AREA  LU_CODE_16  COMMOD       16_AREA
0           0      0.0         652          1.370713e+06
1           0      0.0         210  cattle  1.158460e+07
2           0      0.0         652          1.427609e+05
3           0      0.0         113          3.356297e+04
4           0      0.0         652          7.526508e+05

In [7]:
marrakai0816.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 147 entries, 0 to 146
Data columns (total 11 columns):
codes               5 non-null object
description         4 non-null object
Property            34 non-null object
Property Area m2    0 non-null float64
commodity           0 non-null float64
Isolated m2         35 non-null float64
codes.1             146 non-null float64
description.1       147 non-null object
Total m2            123 non-null float64
commodity.1         75 non-null object
Commodity m2        75 non-null float64
dtypes: float64(6), object(5)
memory usage: 12.7+ KB

In [18]:
df.fillna({'codes': NaN, 'description': NaN})

,codes,description,Property,Property Area m2,commodity,Isolated m2,codes.1,description.1,Total m2,commodity.1,Commodity m2
0,0,NaN,NaN,NaN,NaN,NaN,113.0,National park,2.115370e+07,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,125.0,Traditional indigenous uses,1.500568e+07,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,133.0,Residual native cover,1.236465e+07,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,210.0,Grazing native vegetation,1.156794e+08,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,320.0,Grazing modified pastures,1.612920e+06,Undefined,9.916301e+04
5,NaN,NaN,NaN,NaN,NaN,NaN,320.0,Grazing modified pastures,NaN,cattle,1.296304e+06
6,NaN,NaN,NaN,NaN,NaN,NaN,320.0,Grazing modified pastures,NaN,goats,7.666058e+04
7,NaN,NaN,NaN,NaN,NaN,NaN,320.0,Grazing modified pastures,NaN,horses,6.989188e+04
8,NaN,NaN,NaN,NaN,NaN,NaN,320.0,Grazing modified pastures,NaN,"pigs, goats, poultry & buffalo",7.090092e+04
9,NaN,NaN,NaN,NaN,NaN,NaN,364.0,No defined use,5.487598e+05,NaN,NaN
10,NaN,NaN,NaN,NaN,NaN,NaN,441.0,Irrigated tree fruits,1.125698e+04,Undefined,6.164839e+02
11,NaN,NaN,NaN,NaN,NaN,NaN,441.0,Irrigated tree fruits,NaN,bananas,5.483707e+03
12,NaN,NaN,NaN,NaN,NaN,NaN,441.0,Irrigated tree fruits,NaN,mangoes,7.298663e+05
13,NaN,NaN,NaN,NaN,NaN,NaN,444.0,Irrigated vine fruits,1.125698e+04,dragon fruit,1.125698e+04
14,NaN,NaN,NaN,NaN,NaN,NaN,447.0,Irrigated perennial vegetables and herbs,8.322067e+03,NaN,NaN
15,NaN,NaN,NaN,NaN,NaN,NaN,453.0,Irrigated seasonal vegetables and herbs,1.795066e+06,Undefined,5.055953e+05
16,NaN,NaN,NaN,NaN,NaN,NaN,453.0,Irrigated seasonal vegetables and herbs,NaN,beans,1.930765e+05
17,NaN,NaN,NaN,NaN,NaN,NaN,453.0,Irrigated seasonal vegetables and herbs,NaN,cucumbers,1.056531e+04
18,NaN,NaN,NaN,NaN,NaN,NaN,453.0,Irrigated seasonal vegetables and herbs,NaN,melons,4.424880e+05
19,NaN,NaN,NaN,NaN,NaN,NaN,453.0,Irrigated seasonal vegetables and herbs,NaN,okra,6.008063e+05
20,NaN,NaN,NaN,NaN,NaN,NaN,453.0,Irrigated seasonal vegetables and herbs,NaN,taro,1.319735e+04
21,NaN,NaN,NaN,NaN,NaN,NaN,453.0,Irrigated seasonal vegetables and herbs,NaN,zucchini,2.933742e+04
22,NaN,NaN,NaN,NaN,NaN,NaN,464.0,No defined use - irrigation,8.268190e+05,NaN,NaN
23,NaN,NaN,NaN,NaN,NaN,NaN,465.0,Abandoned irrigated perennial horticulture,1.895358e+04,NaN,NaN
24,NaN,NaN,NaN,NaN,NaN,NaN,512.0,Shadehouses,8.066767e+04,cucumbers,8.066767e+04
25,NaN,NaN,NaN,NaN,NaN,NaN,542.0,Rural residential with agriculture,9.653614e+06,NaN,NaN
26,4.4.0,Irrigated perennial horticulture,000 05280,NaN,NaN,81331.969600,441.0,Irrigated tree fruits,3.926189e+04,mangoes,3.926189e+04
27,NaN,NaN,NaN,NaN,NaN,NaN,453.0,Irrigated seasonal vegetables and herbs,7.912414e+04,okra,7.912414e+04
28,NaN,NaN,NaN,NaN,NaN,NaN,542.0,Rural residential with agriculture,1.727912e+05,NaN,NaN
29,NaN,NaN,000 05282,NaN,NaN,58870.760890,441.0,Irrigated tree fruits,3.734096e+04,mangoes,3.734096e+04
...,...,...,...,...,...,...,...,...,...,...,...
117,NaN,NaN,NaN,NaN,NaN,NaN,441.0,Irrigated tree fruits,NaN,mangoes,1.201634e+05
118,NaN,NaN,NaN,NaN,NaN,NaN,453.0,Irrigated seasonal vegetables and herbs,NaN,melons,6.438302e+04
119,NaN,NaN,NaN,NaN,NaN,NaN,542.0,Rural residential with agriculture,2.758414e+05,NaN,NaN
120,NaN,NaN,NaN,NaN,NaN,NaN,572.0,Roads,4.843477e+06,NaN,NaN
121,NaN,NaN,000 05307,NaN,NaN,25788.573040,441.0,Irrigated tree fruits,5.483707e+03,bananas,5.483707e+03
122,NaN,NaN,NaN,NaN,NaN,NaN,453.0,Irrigated seasonal vegetables and herbs,2.849805e+04,NaN,NaN
123,NaN,NaN,NaN,NaN,NaN,NaN,464.0,No defined use - irrigation,1.247731e+04,NaN,NaN
124,NaN,NaN,NaN,NaN,NaN,NaN,542.0,Rural residential with agriculture,3.930938e+04,NaN,NaN
125,NaN,NaN,000 05562,NaN,NaN,3766.895684,441.0,Irrigated tree fruits,9.564650e+03,mangoes,9.564650e+03
126,NaN,NaN,NaN,NaN,NaN,NaN,453.0,Irrigated seasonal vegetables and herbs,7.639566e+03,okra,7.639566e+03
127,NaN,NaN,NaN,NaN,NaN,NaN,542.0,Rural residential with agriculture,1.567463e+04,NaN,NaN
128,NaN,NaN,0001 05398,NaN,NaN,64288.309720,320.0,Grazing modified pastures,2.728137e+04,goats,2.728137e+04
129,NaN,NaN,NaN,NaN,NaN,NaN,441.0,Irrigated tree fruits,4.291884e+03,NaN,NaN
130,NaN,NaN,NaN,NaN,NaN,NaN,448.0,Irrigated citrus,7.138846e+03,limes,7.138846e+03
131,NaN,NaN,NaN,NaN,NaN,NaN,453.0,Irrigated seasonal vegetables and herbs,1.789375e+04,undefined,6.162689e+03
132,NaN,NaN,NaN,NaN,NaN,NaN,453.0,Irrigated seasonal vegetables and herbs,NaN,vegetables,1.173107e+04
133,NaN,NaN,NaN,NaN,NaN,NaN,542.0,Rural residential with agriculture,7.679120e+03,NaN,NaN
134,NaN,NaN,NaN,NaN,NaN,NaN,543.0,Rural residential without agriculture,6.405370e+04,NaN,NaN
135,NaN,NaN,NaN,NaN,NaN,NaN,572.0,Roads,4.843477e+06,NaN,NaN
136,4.6.0,Irrigated land in transition,000 03099,NaN,NaN,254160.998000,210.0,Grazing native vegetation,6.107402e+04,cattle,6.107402e+04
137,NaN,NaN,NaN,NaN,NaN,NaN,320.0,Grazing modified pastures,4.485719e+05,cattle,4.485719e+05
138,NaN,NaN,NaN,NaN,NaN,NaN,441.0,Irrigated tree fruits,2.570258e+05,mangoes,2.570258e+05
139,NaN,NaN,NaN,NaN,NaN,NaN,542.0,Rural residential with agriculture,1.259913e+05,NaN,NaN
140,NaN,NaN,NaN,NaN,NaN,NaN,543.0,Rural residential without agriculture,3.559415e+04,NaN,NaN
141,NaN,NaN,000 05530,NaN,NaN,10019.980280,542.0,Rural residential with agriculture,2.245804e+05,NaN,NaN
142,NaN,NaN,000 05539,NaN,NaN,15632.375060,133.0,Residual native cover,1.006347e+07,NaN,NaN
143,NaN,NaN,NaN,NaN,NaN,NaN,542.0,Rural residential with agriculture,2.132942e+05,NaN,NaN
144,NaN,NaN,000 05544,NaN,NaN,25541.321540,320.0,Grazing modified pastures,5.513377e+04,horses,5.513377e+04
145,NaN,NaN,NaN,NaN,NaN,NaN,543.0,Rural residential without agriculture,6.538515e+04,NaN,NaN
146,NaN,NaN,NaN,NaN,NaN,NaN,572.0,Roads,4.843477e+06,NaN,NaN

In [17]:
df

,codes,description,Property,Property Area m2,commodity,Isolated m2,codes.1,description.1,Total m2,commodity.1,Commodity m2
0,0,NaN,NaN,NaN,NaN,NaN,113.0,National park,2.115370e+07,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,125.0,Traditional indigenous uses,1.500568e+07,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,133.0,Residual native cover,1.236465e+07,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,210.0,Grazing native vegetation,1.156794e+08,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,320.0,Grazing modified pastures,1.612920e+06,Undefined,9.916301e+04
5,NaN,NaN,NaN,NaN,NaN,NaN,320.0,Grazing modified pastures,NaN,cattle,1.296304e+06
6,NaN,NaN,NaN,NaN,NaN,NaN,320.0,Grazing modified pastures,NaN,goats,7.666058e+04
7,NaN,NaN,NaN,NaN,NaN,NaN,320.0,Grazing modified pastures,NaN,horses,6.989188e+04
8,NaN,NaN,NaN,NaN,NaN,NaN,320.0,Grazing modified pastures,NaN,"pigs, goats, poultry & buffalo",7.090092e+04
9,NaN,NaN,NaN,NaN,NaN,NaN,364.0,No defined use,5.487598e+05,NaN,NaN
10,NaN,NaN,NaN,NaN,NaN,NaN,441.0,Irrigated tree fruits,1.125698e+04,Undefined,6.164839e+02
11,NaN,NaN,NaN,NaN,NaN,NaN,441.0,Irrigated tree fruits,NaN,bananas,5.483707e+03
12,NaN,NaN,NaN,NaN,NaN,NaN,441.0,Irrigated tree fruits,NaN,mangoes,7.298663e+05
13,NaN,NaN,NaN,NaN,NaN,NaN,444.0,Irrigated vine fruits,1.125698e+04,dragon fruit,1.125698e+04
14,NaN,NaN,NaN,NaN,NaN,NaN,447.0,Irrigated perennial vegetables and herbs,8.322067e+03,NaN,NaN
15,NaN,NaN,NaN,NaN,NaN,NaN,453.0,Irrigated seasonal vegetables and herbs,1.795066e+06,Undefined,5.055953e+05
16,NaN,NaN,NaN,NaN,NaN,NaN,453.0,Irrigated seasonal vegetables and herbs,NaN,beans,1.930765e+05
17,NaN,NaN,NaN,NaN,NaN,NaN,453.0,Irrigated seasonal vegetables and herbs,NaN,cucumbers,1.056531e+04
18,NaN,NaN,NaN,NaN,NaN,NaN,453.0,Irrigated seasonal vegetables and herbs,NaN,melons,4.424880e+05
19,NaN,NaN,NaN,NaN,NaN,NaN,453.0,Irrigated seasonal vegetables and herbs,NaN,okra,6.008063e+05
20,NaN,NaN,NaN,NaN,NaN,NaN,453.0,Irrigated seasonal vegetables and herbs,NaN,taro,1.319735e+04
21,NaN,NaN,NaN,NaN,NaN,NaN,453.0,Irrigated seasonal vegetables and herbs,NaN,zucchini,2.933742e+04
22,NaN,NaN,NaN,NaN,NaN,NaN,464.0,No defined use - irrigation,8.268190e+05,NaN,NaN
23,NaN,NaN,NaN,NaN,NaN,NaN,465.0,Abandoned irrigated perennial horticulture,1.895358e+04,NaN,NaN
24,NaN,NaN,NaN,NaN,NaN,NaN,512.0,Shadehouses,8.066767e+04,cucumbers,8.066767e+04
25,NaN,NaN,NaN,NaN,NaN,NaN,542.0,Rural residential with agriculture,9.653614e+06,NaN,NaN
26,4.4.0,Irrigated perennial horticulture,000 05280,NaN,NaN,81331.969600,441.0,Irrigated tree fruits,3.926189e+04,mangoes,3.926189e+04
27,NaN,NaN,NaN,NaN,NaN,NaN,453.0,Irrigated seasonal vegetables and herbs,7.912414e+04,okra,7.912414e+04
28,NaN,NaN,NaN,NaN,NaN,NaN,542.0,Rural residential with agriculture,1.727912e+05,NaN,NaN
29,NaN,NaN,000 05282,NaN,NaN,58870.760890,441.0,Irrigated tree fruits,3.734096e+04,mangoes,3.734096e+04
...,...,...,...,...,...,...,...,...,...,...,...
117,NaN,NaN,NaN,NaN,NaN,NaN,441.0,Irrigated tree fruits,NaN,mangoes,1.201634e+05
118,NaN,NaN,NaN,NaN,NaN,NaN,453.0,Irrigated seasonal vegetables and herbs,NaN,melons,6.438302e+04
119,NaN,NaN,NaN,NaN,NaN,NaN,542.0,Rural residential with agriculture,2.758414e+05,NaN,NaN
120,NaN,NaN,NaN,NaN,NaN,NaN,572.0,Roads,4.843477e+06,NaN,NaN
121,NaN,NaN,000 05307,NaN,NaN,25788.573040,441.0,Irrigated tree fruits,5.483707e+03,bananas,5.483707e+03
122,NaN,NaN,NaN,NaN,NaN,NaN,453.0,Irrigated seasonal vegetables and herbs,2.849805e+04,NaN,NaN
123,NaN,NaN,NaN,NaN,NaN,NaN,464.0,No defined use - irrigation,1.247731e+04,NaN,NaN
124,NaN,NaN,NaN,NaN,NaN,NaN,542.0,Rural residential with agriculture,3.930938e+04,NaN,NaN
125,NaN,NaN,000 05562,NaN,NaN,3766.895684,441.0,Irrigated tree fruits,9.564650e+03,mangoes,9.564650e+03
126,NaN,NaN,NaN,NaN,NaN,NaN,453.0,Irrigated seasonal vegetables and herbs,7.639566e+03,okra,7.639566e+03
127,NaN,NaN,NaN,NaN,NaN,NaN,542.0,Rural residential with agriculture,1.567463e+04,NaN,NaN
128,NaN,NaN,0001 05398,NaN,NaN,64288.309720,320.0,Grazing modified pastures,2.728137e+04,goats,2.728137e+04
129,NaN,NaN,NaN,NaN,NaN,NaN,441.0,Irrigated tree fruits,4.291884e+03,NaN,NaN
130,NaN,NaN,NaN,NaN,NaN,NaN,448.0,Irrigated citrus,7.138846e+03,limes,7.138846e+03
131,NaN,NaN,NaN,NaN,NaN,NaN,453.0,Irrigated seasonal vegetables and herbs,1.789375e+04,undefined,6.162689e+03
132,NaN,NaN,NaN,NaN,NaN,NaN,453.0,Irrigated seasonal vegetables and herbs,NaN,vegetables,1.173107e+04
133,NaN,NaN,NaN,NaN,NaN,NaN,542.0,Rural residential with agriculture,7.679120e+03,NaN,NaN
134,NaN,NaN,NaN,NaN,NaN,NaN,543.0,Rural residential without agriculture,6.405370e+04,NaN,NaN
135,NaN,NaN,NaN,NaN,NaN,NaN,572.0,Roads,4.843477e+06,NaN,NaN
136,4.6.0,Irrigated land in transition,000 03099,NaN,NaN,254160.998000,210.0,Grazing native vegetation,6.107402e+04,cattle,6.107402e+04
137,NaN,NaN,NaN,NaN,NaN,NaN,320.0,Grazing modified pastures,4.485719e+05,cattle,4.485719e+05
138,NaN,NaN,NaN,NaN,NaN,NaN,441.0,Irrigated tree fruits,2.570258e+05,mangoes,2.570258e+05
139,NaN,NaN,NaN,NaN,NaN,NaN,542.0,Rural residential with agriculture,1.259913e+05,NaN,NaN
140,NaN,NaN,NaN,NaN,NaN,NaN,543.0,Rural residential without agriculture,3.559415e+04,NaN,NaN
141,NaN,NaN,000 05530,NaN,NaN,10019.980280,542.0,Rural residential with agriculture,2.245804e+05,NaN,NaN
142,NaN,NaN,000 05539,NaN,NaN,15632.375060,133.0,Residual native cover,1.006347e+07,NaN,NaN
143,NaN,NaN,NaN,NaN,NaN,NaN,542.0,Rural residential with agriculture,2.132942e+05,NaN,NaN
144,NaN,NaN,000 05544,NaN,NaN,25541.321540,320.0,Grazing modified pastures,5.513377e+04,horses,5.513377e+04
145,NaN,NaN,NaN,NaN,NaN,NaN,543.0,Rural residential without agriculture,6.538515e+04,NaN,NaN
146,NaN,NaN,NaN,NaN,NaN,NaN,572.0,Roads,4.843477e+06,NaN,NaN